### ISSUE TITLE
Webhook mocks/fixtures

### ISSUE THREAD

**Issue by rtsao** [gr2m/octokit-webhooks.js-legacy#8]
Per https://github.com/probot/probot/issues/316#issue-271571092, for testing probot apps, it would be ideal to have a `node-github`-like API to programmatically generate webhook fixtures, for example something like:

```js
let robot = /* ... */

let github = new MockGitHub();
let repo = github.mocks.repo({
  org: 'test-org',
  name: 'test-repo'
});

robot.auth = () => Promise.resolve(github);

let webhook = github.issues.edited(
  repo.issue({
    body: 'new issue body'
  })
);

await robot.recieve(webhook);

/* ... assertions ... */

```

**Comment by JasonEtco** [comment]
Related: @gr2m has been working on a [fixtures](https://github.com/octokit/fixtures) repo for use with `node-github`; I'm guessing it can be used with webhook mocks as well.

**Comment by gr2m** [comment]
hey friends, yes, I’m thinking about fixtures for webhooks, too.

@rtsao thanks for the dream code, I love discussions based on idea code like that :)

I’ll get back to you soon

**Comment by rtsao** [comment]
Awesome! 😄

**Comment by gr2m** [comment]
moved to https://github.com/octokit/webhooks.js/issues/7 :)
